$(function() {
	//发活动
	$('#activities').hover(function(){
		$(this).attr('src','image/02/btn_1_pressed.png');
		$('#pics').attr('src','image/02/001.png');
	},function(){
		$(this).attr('src','image/02/btn_1_normal.png');
		$('#pics').attr('src','image/02/001.png');
	})
	//发探索
	$('#discover').hover(function(){
		$(this).attr('src','image/02/btn_2_pressed.png');
		$('#pics').attr('src','image/02/002.png');
	},function(){
		$(this).attr('src','image/02/btn_2_normal.png');
		$('#pics').attr('src','image/02/001.png');
	})
	//建圈子
	$('#buildCircle').hover(function(){
		$(this).attr('src','image/02/btn_3_pressed.png');
		$('#pics').attr('src','image/02/003.png');
	},function(){
		$(this).attr('src','image/02/btn_3_normal.png');
		$('#pics').attr('src','image/02/001.png');
	})
	//发图文
	$('#sendText').hover(function(){
		$(this).attr('src','image/02/btn_4_pressed.png');
		$('#pics').attr('src','image/02/004.png');
	},function(){
		$(this).attr('src','image/02/btn_4_normal.png');
		$('#pics').attr('src','image/02/001.png');
	})
})